// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjXiDz88gN-wlEy1b4upiBjMrSWUq6VEg',
    appId: '1:779394133531:web:bd37a1bb850101da3352be',
    messagingSenderId: '779394133531',
    projectId: 'bazaar-010',
    authDomain: 'bazaar-010.firebaseapp.com',
    storageBucket: 'bazaar-010.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjW3bumM7OEm79rdoiO89nF0RSkevUSag',
    appId: '1:779394133531:android:b252d5f9edd0f3b03352be',
    messagingSenderId: '779394133531',
    projectId: 'bazaar-010',
    storageBucket: 'bazaar-010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAEC0fxTscPCOkSSB9SR7hskU9gIqsHPQ',
    appId: '1:779394133531:ios:58918e495669f3f33352be',
    messagingSenderId: '779394133531',
    projectId: 'bazaar-010',
    storageBucket: 'bazaar-010.appspot.com',
    iosBundleId: 'com.example.bazaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAEC0fxTscPCOkSSB9SR7hskU9gIqsHPQ',
    appId: '1:779394133531:ios:58918e495669f3f33352be',
    messagingSenderId: '779394133531',
    projectId: 'bazaar-010',
    storageBucket: 'bazaar-010.appspot.com',
    iosBundleId: 'com.example.bazaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjXiDz88gN-wlEy1b4upiBjMrSWUq6VEg',
    appId: '1:779394133531:web:d8d1525dbdc8a2de3352be',
    messagingSenderId: '779394133531',
    projectId: 'bazaar-010',
    authDomain: 'bazaar-010.firebaseapp.com',
    storageBucket: 'bazaar-010.appspot.com',
  );
}
